In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
a=np.array([1,2,3])
print(a)


[1 2 3]


In [7]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [8]:
# minimum dimensions
a=np.array([1, 2, 3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [9]:
a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [10]:
dt=np.dtype(np.int32)
print(dt)

int32


In [11]:
dt = np.dtype('i4')
print(dt)

int32


In [12]:
dt = np.dtype('>i4')
print( dt)

>i4


In [13]:
dt = np.dtype([('age',np.int8)])
print (dt)

[('age', 'i1')]


In [14]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
print (a)

[(10,) (20,) (30,)]


In [15]:
student=np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
print (student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [16]:
student=np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [17]:
a=np.array([[1,2,3],[4,5,6]])
print (a.shape)

(2, 3)


In [18]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
a = np.arange(24)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [21]:
a = np.arange(24)
a.ndim
b = a.reshape(2,4,3)
print (b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [24]:
x = np.array([1,2,3,4,5], dtype=np.float32)
print (x.itemsize)

4


In [25]:
x = np.empty([3,2], dtype=int)
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
x = np.zeros(5)
print (x)

[0. 0. 0. 0. 0.]


In [27]:
x = np.ones(5)
print (x)

[1. 1. 1. 1. 1.]


In [28]:
x = np.ones([2,2], dtype=int)
print (x)

[[1 1]
 [1 1]]


In [29]:
x = [1,2,3]
a = np.asarray(x)
print (a)

[1 2 3]


In [30]:
x = [1,2,3]
a = np.asarray(x, dtype=float)
print (a)

[1. 2. 3.]


In [35]:
list = range(5)
print (list)

range(0, 5)


In [36]:
list = range(5)
it = iter(list)
x = np.fromiter(it, dtype=float)
print (x)

[0. 1. 2. 3. 4.]


In [42]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [43]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [46]:
a = np.matrix(np.ones((4,4)))
np.array(a)[2]=2
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [48]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [49]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [54]:
#Indexing and slicing
e  = np.array([(1,2,3), (4,5,6)])
print(e)
print('First row:', e[0])
print('Second row:', e[1])
print('Second column:', e[:,1])
print(e[1, :2])

[[1 2 3]
 [4 5 6]]
First row: [1 2 3]
Second row: [4 5 6]
Second column: [2 5]
[4 5]


In [ ]:
#NumPy Statistical Functions

In [55]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.55483923 4.60256736 5.09635425 5.45305865 5.64517377 5.1188137
 5.44728119 6.05773427 4.70472231 4.46257437]


In [56]:
print(np.min(normal_array))

4.462574368578618


In [57]:
print(np.max(normal_array))

6.057734268478942


In [58]:
print(np.mean(normal_array))

5.2143119101675754


In [60]:
print(np.median(normal_array))

5.283047447917452


In [59]:
print(np.std(normal_array))

0.48438548384663255


In [ ]:
#Numpy Dot Product Function

In [61]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)

14

In [ ]:
# Matrix Multiplication

In [62]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [63]:
#Simple Array Operations

In [64]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [65]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [66]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
u = np.eye(2)
print(u)

[[1. 0.]
 [0. 1.]]


In [69]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

print(j @ j)

[[-1.  0.]
 [ 0. -1.]]


In [72]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [74]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [78]:
a = np.array( [20,30,40,50] )
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [79]:
b = np.arange( 4 )
print(b)
print(b**2)

[0 1 2 3]
[0 1 4 9]


In [ ]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
print(a *= 3)
print(a)

In [ ]:
b = rg.random((2,3))
print(b += a)
print(b)

In [81]:
rg = np.random.default_rng(1)
a = rg.random((2,3))
print(a)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [83]:
b = np.arange(12).reshape(3,4)
b.cumsum(axis=1) 

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [84]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])